version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: production
    groups:
      acmekit:
        patterns:
        - "@acmekit*"
        - "acmekit*"
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "@acmekit*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "acmekit*"
        update-types: ["version-update:semver-major"]
